import { describe, expect, it } from 'vitest';

import { firstRealPromptText, isInjectedPrompt } from './prompt';

describe('isInjectedPrompt', () => {
  it.each([
    '<local-command-caveat>Caveat: The messages below were generated by the user…',
    '<command-name>/clear</command-name>',
    '  <system-reminder>background task event</system-reminder>',
    '<bash-stdout>ok</bash-stdout>',
  ])('recognizes harness-injected machinery: %s', (text) => {
    expect(isInjectedPrompt(text)).toBe(true);
  });

  it.each([
    'read the memory and continue T7',
    'fix the <Button> component',
    '<div> is rendering twice — why?',
    '',
    // A known tag NAME as a prefix of an unknown tag is not a hit — the name must end at the match.
    '<command-name-extra>note</command-name-extra>',
    '<local-command-caveat-custom>text',
  ])('never flags a real human prompt: %s', (text) => {
    expect(isInjectedPrompt(text)).toBe(false);
  });
});

describe('firstRealPromptText', () => {
  it('returns the first user entry that is not injected machinery', () => {
    expect(
      firstRealPromptText([
        { kind: 'user', text: '<local-command-caveat>Caveat: generated by the user…' },
        { kind: 'tool' },
        { kind: 'user', text: 'fix the pairing race' },
      ]),
    ).toBe('fix the pairing race');
  });

  it('returns undefined when every user entry is machinery (or there are none)', () => {
    expect(
      firstRealPromptText([
        { kind: 'user', text: '<system-reminder>tick</system-reminder>' },
        { kind: 'message', text: 'assistant reply' },
      ]),
    ).toBeUndefined();
    expect(firstRealPromptText([])).toBeUndefined();
  });
});
